export const normalizedNames: Record<string, string> = {
    'Fiddlesticks': 'FiddleSticks',
    'Aurelion Sol': 'AurelionSol',
    'Jarvan IV': 'JarvanIV',
    'K\'Sante': 'KSante',
    'Kha\'Zix': 'Khazix',
    'Kog\'Maw': 'KogMaw',
    'Kai\'Sa': 'Kaisa',
    'Rek\'Sai': 'RekSai',
    'Tahm Kench': 'TahmKench',
    'Nunu e Willump': 'Nunu',
    'Master Yi': 'MasterYi',
    'Miss Fortune': 'MissFortune',
    'Renata Glasc': 'Renata',
    'Twisted Fate': 'TwistedFate',
    'Vel\'Koz': 'Velkoz',
    'Xin Zhao': 'XinZhao',
    'Cho\'Gath': 'Chogath',
    'Dr. Mundo': 'DrMundo',
}